### ISSUE TITLE
Running the efficient mapping with qiskit vqe

### ISSUE THREAD

**Issue by zlilyoffe** [m24639297/qubit-efficient-mapping#6]
Hi,
could you please publish your full VQE code that you had run with qiskit?
because you used qiskit.aqua (which is deprecated) i cant really use you code and run a VQE circuit.

i am trying to recreate the results that appear in a paper by you - 
A Qubit-Efficient Encoding Scheme for
Quantum Simulations of Electronic Structure

Thanks

**Comment by randyshee** [comment]
Hi,

Thank you so much for your interest to recreate the results. I have added a notebook in the repo where you will be able to see a VQE example for a H2 molecule in the 6-31G basis set. Let me know if you need anything else.

[https://github.com/m24639297/qubit-efficient-mapping/blob/master/H2_631G_VQE_Example.ipynb](url)

Best,
Yu (Randy) Shee

**Comment by zlilyoffe** [comment]
Thank you very much
